# schema.yml
version: 2
sources: 
   - name: raw
     database: sapient-codex-485210-a6
     schema: gz_raw_data
     loader: bigquery
     description: tables_ventes_prduits 
     tables:
       - name: sales
         identifier: raw_gz_sales
       - name: product
         identifier: raw_gz_product
       - name: ship
         identifier: raw_gz_ship
